{
 "title": "Plex",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bandwidth",
     "select": [
      [
       { "params": [ "download_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bandwidth",
     "select": [
      [
       { "params": [ "upload_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "region_code" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bandwidth",
     "select": [
      [
       { "params": [ "upload_bitrate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bandwidth",
     "select": [
      [
       { "params": [ "download_bitrate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ]
    }
   ]
  },
  {
   "title": "Plex CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "plex",
     "select": [
      [
       { "params": [ "CPU Utilization" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "Plex" }
     ]
    }
   ]
  },
  {
   "title": "Plex Current Streams",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ]
    }
   ]
  },
  {
   "title": "SAN IO_Wait",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Storage Servers",
     "select": [
      [
       { "params": [ "IO_Wait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "SAN3" }
     ]
    }
   ]
  },
  {
   "title": "TV / Movie Requests in Queue",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "quality" ], "type": "field" }
      ],
      [
       { "params": [ "transcode_decision" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Missing TV Shows",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "title": "Missing Movies",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  }
 ]
}