{
 "title": "Varken Alt Dashboard",
 "description": "Dashboard for Varken using InfluxDB v2 and Flux",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB", "query": "influxdb" },
   {
    "name": "Radarr",
    "query": "https://movies.yourdomain.com:7878"
   },
   { "name": "Sonarr", "query": "https://tv.yourdomain.com:7878" },
   {
    "name": "Tautulli",
    "query": "https://tautulli.yourdomain.com:8181"
   },
   {
    "name": "Ombi",
    "query": "https://ombi.yourdomain.com:5000"
   },
   { "name": "movieslibrary", "label": "Movies Library Name", "query": "Movies" },
   { "name": "tvlibrary", "label": "TV Show Library Name", "query": "TV Shows" },
   { "name": "movies4klibrary", "label": "4k Movie Library Name", "query": "Movies 4K" },
   { "name": "tv4klibrary", "label": "4k TV Library Name", "query": "TV Shows 4K" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(plays_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(plays_total{job=~\"$job\", instance=~\"$instance\"},server)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"direct_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"transcode_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"direct_play_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "host_cpu_util" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "host_mem_util" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r.section_name == \"${movieslibrary}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"movie\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tvlibrary}\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "4K TV Shows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tv4klibrary}\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"stream_count\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "4K Movies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) => r.section_name == \"${movies4klibrary}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"movie\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"seasons\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tvlibrary}\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "4K TV Seasons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"seasons\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tv4klibrary}\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server\", fstype=~\"ext.*|xfs\", mountpoint!~\".*pod.*\"} - 0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server\", fstype=~\"ext.*|xfs\", mountpoint!~\".*pod.*\"} - 0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"friendly_name\", \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"friendly_name\", \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total Library Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(library_storage_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\"})",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"episodes\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tvlibrary}\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "4K TV Episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"episodes\")\r\n  |> filter(fn: (r) => r[\"section_name\"] == \"${tv4klibrary}\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> filter(fn: (r) => r[\"server\"] == \"1\")\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Radarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Queue\")\r\n  |> group(columns: [\"name\", \"protocol_id\", \"quality\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"name\", \"protocol_id\", \"quality\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"pending\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Req. Approved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"approved\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Req. Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"available\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 12 },
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Device Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"device_type\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"device_type\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"video_decision\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"video_decision\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Queue\")\r\n  |> group(columns: [\"protocol_id\", \"sxe\", \"name\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"protocol_id\", \"sxe\", \"name\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Missing TV Shows (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Missing\")\r\n  |> group(columns: [\"server\", \"sxe\", \"name\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Radarr\")\r\n  |> filter(fn: (r) => r[\"Missing_Available\"] == \"0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hash\")\r\n  |> group(columns: [\"name\", \"titleSlug\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "TV Shows on Today (Sonarr)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Future\")\r\n  |> group(columns: [\"downloaded\", \"name\", \"sxe\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"downloaded\", \"name\", \"sxe\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "WIP Panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Popularity",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> group(columns: [\"_time\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: distinct, createEmpty: false)\r\n  |> count()\r\n  |> fill(value: 0)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])"
      }
     ]
    },
    {
     "title": "Ombi Requests Pending",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 63 },
     "targets": [
      {
       "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Requests\")\r\n  |> filter(fn: (r) => r.status != 0)\r\n  |> filter(fn: (r) => r.status != 2)\r\n  |> group(columns: [\"title\", \"requested_date\", \"requested_user\", \"request_type\", \"status\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"title\", \"requested_date\", \"requested_user\", \"request_type\", \"status\"])\r\n  |> sort(columns: [\"_time\"])"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "options": {
      "content": "# THIS DASHBOARD IS NOT COMPATIBLE WITH InfluxQL!\n\n## Notes\nThis dashboard is a WIP and is not 100% complete. It relies on a specific build of Varken using a PR for InfluxDB v2 Support. This dashboard is for dev testing InfluxDB v2 support and updated to support Grafana v9+. Not all features from the v1.6.x of Varken's dashboard are supported.\n\nMost panels are in working order with minor issues. Panels that are still WIP are collapsed in a row at the bottom. If you are familiar with Flux queries feel free to submit a PR to update the dev dashboard! :)\n\n## How to use\nUpdate the variables in this dashboard's settings to reflect your environment. Then save it!"
     }
    },
    {
     "type": "geomap",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 78 },
     "targets": [
      {
       "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"latitude\", \"longitude\", \"full_location\", \"name\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"latitude\", \"longitude\", \"full_location\", \"name\"])\r\n  |> sort(columns: [\"_time\"])\r\n"
      }
     ]
    }
   ]
  }
 ]
}